### ISSUE TITLE
Cors error 

### ISSUE THREAD

**Issue by SGoineanu** [cooolr/chatgpt_proxy_website#3]
Could you please fix the CORS error? Also, it looks like there is a 429 error when accessing resources.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/19905292/221906802-00f175e8-21d8-40dd-b1af-f7acb880e23b.png">

**Comment by cooolr** [comment]
> Could you please fix the CORS error? Also, it looks like there is a 429 error when accessing resources.
> 
> <img alt="image" width="401" src="https://user-images.githubusercontent.com/19905292/221906802-00f175e8-21d8-40dd-b1af-f7acb880e23b.png">

@SGoineanu `puid` `cf_clearance` `session_token` Have you filled in these three parameters?

**Comment by SGoineanu** [comment]
Yes, I did
