### ISSUE TITLE
运行报错：KeyError: 'user'

### ISSUE THREAD

**Issue by orwithout** [cooolr/chatgpt_proxy_website#4]
adduser chat
su - chat
cd ~
git clone https://github.com/cooolr/chatgpt_proxy_website.git
cd chatgpt_proxy_website
pip install -r requirements.txt
vim  chatgpt_proxy_website.py :
![image](https://user-images.githubusercontent.com/19142891/222037352-e68c2fa3-fb93-4579-8660-38f2bcd447de.png)

python3 chatgpt_proxy_website.py   :
![image](https://user-images.githubusercontent.com/19142891/222038717-4c1453ef-0231-4590-97df-65e763d1d66a.png)

什么原因呢？

**Comment by cooolr** [comment]
@orwithout `session_token` 是必须的。

**Comment by orwithout** [comment]
启动了，但是登录失败：
![image](https://user-images.githubusercontent.com/19142891/222040307-f4ebd671-737d-40c3-b4d2-e6389dde93ba.png)

**Comment by cooolr** [comment]
> 启动了，但是登录失败： ![image](https://user-images.githubusercontent.com/19142891/222040307-f4ebd671-737d-40c3-b4d2-e6389dde93ba.png)

@orwithout user_id留空代表不启用登录验证哇，这一块我偷懒没有处理，你在url后面加/chat就可以直达页面了。http://127.0.0.1:8011/chat

**Comment by cooolr** [comment]
@orwithout 这个逻辑我已经修复了，user_id留空会跳转到/chat，感谢反馈。

**Comment by orwithout** [comment]
原来是这样……要想像cooolr.online一样，允许用户使用自己的chatGPT账号，应该怎么设置？配置里不应该写定session_token ？

**Comment by cooolr** [comment]
自动登录那一块的逻辑我在auth.py里面完成了，设想是用chatgpt账号密码获取sesstion_token，cf_clearance好像不用也可以，但是在使用过程中发现不太稳定，有时候会获取失败，为了项目的稳定性，我把没引用起来，cooolr.online在尝试用户使用自己的chatGPT账号的过程中，出现了串号的问题，登录到别人的账号，所以现在还是手动维护session_token的，我就和几个朋友们在用，太菜了，做不到像apiaia那样。

**Comment by cooolr** [comment]
> session_token 、puid 、cf_clearance 这几个值应该也会有过期时间吧？

puid一个星期过期，session_token好像一个月

**Comment by cooolr** [comment]
我不打算续费plus了，感觉notion ai的生产力更强一点，虽然用的是gpt3，但我用chatgpt很多都局限在讨论，它参与不到我的生产力里面来，让他写的代码问题多多，我把notion ai的api抓出来准备用在chatgpt的页面上

**Comment by orwithout** [comment]
你这可能就是一些细节问题了，比如是不是可以服务端给信号，让客户端的浏览器主动清理掉cookie缓存？这样解决串号问题？apiaiai不开源，说不定这个站长就是后台每天手动更新puid啥之类的呢，他都不开源，谁知道呢……

**Comment by cooolr** [comment]
已经修复。
